# Generated by Django 3.2.9 on 2021-12-02 15:03

import WorkApp.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[WorkApp.validators.validate_correct_client_id])),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('client_type', models.CharField(choices=[('первичный', 'первичный'), ('повторный', 'повторный'), ('внешний', 'внешний'), ('косвенный', 'косвенный')], max_length=16)),
                ('gender', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский'), ('неизвестно', 'неизвестно')], max_length=16)),
                ('timezone', models.CharField(choices=[('Москва', '+3:00'), ('Украина', '+4:00')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('second_name', models.CharField(max_length=32)),
                ('third_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworksUniq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=32)),
                ('social_name', models.CharField(choices=[('OK', 'OK'), ('Instagram', 'Instagram'), ('Telegram', 'Instagram'), ('WhatsApp', 'WhatsApp'), ('Viber', 'Viber')], max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkApp.client')),
            ],
            options={
                'unique_together': {('owner', 'social_name')},
            },
        ),
        migrations.CreateModel(
            name='SocialNetworksNotUniq',
            fields=[
                ('socialnetworksuniq_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WorkApp.socialnetworksuniq')),
                ('social_name_not_uniq', models.CharField(choices=[('VK', 'VK'), ('FB', 'FB')], max_length=16, verbose_name='social_name')),
            ],
            options={
                'abstract': False,
            },
            bases=('WorkApp.socialnetworksuniq',),
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[WorkApp.validators.validate_correct_legal_person_id])),
                ('full_title', models.CharField(max_length=64)),
                ('short_title', models.CharField(max_length=32)),
                ('INN', models.IntegerField()),
                ('KPP', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, validators=[WorkApp.validators.validate_correct_department])),
                ('title', models.CharField(max_length=32)),
                ('clients', models.ManyToManyField(to='WorkApp.Client')),
                ('owners', models.ManyToManyField(to='WorkApp.LegalPerson')),
                ('parent_department', models.ForeignKey(blank=True, help_text='родитель нового департамента', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='WorkApp.departments')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WorkApp.names'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
